#ifndef SIZEWEIGHTDEFINITIONS_H_
#define SIZEWEIGHTDEFINITIONS_H_

#define OUTPUT_IMAGE_REF_TXT "/home/anson/ZynqProjects/images/FullyConvoultionalLayer/FilterResultARM.txt"
#define OUTPUT_IMAGE_TXT "/home/anson/ZynqProjects/images/FullyConvoultionalLayer/FilterResultAcc.txt"

// 3x3 kernel
#define KERNEL_DIM 3

#define IMG_WIDTH_OR_COLS 112
#define IMG_HEIGHT_OR_ROWS 82
#define INPUT_IMG_CHANNELS 3
#define OUT_IMG_WIDTH_OR_COLS (IMG_WIDTH_OR_COLS - KERNEL_DIM + 1)
#define OUT_IMG_HEIGHT_OR_ROWS (IMG_HEIGHT_OR_ROWS - KERNEL_DIM + 1)
#define OUTPUT_IMG_CHANNELS 16

#define INPUT_SIZE (IMG_HEIGHT_OR_ROWS * IMG_WIDTH_OR_COLS * INPUT_IMG_CHANNELS)
#define WEIGHT_SIZE (OUTPUT_IMG_CHANNELS * INPUT_IMG_CHANNELS * KERNEL_DIM * KERNEL_DIM)
#define BIAS_SIZE (OUTPUT_IMG_CHANNELS)
#define OUTPUT_SIZE (OUT_IMG_HEIGHT_OR_ROWS * OUT_IMG_WIDTH_OR_COLS * OUTPUT_IMG_CHANNELS)



#endif /* SIZEWEIGHTDEFINITIONS_H_ */
